<?php include VIEW . 'header.phtml';?>

<h1> Index view</h1>

<?php
    echo '<h2>Welcome to <span style="color:#62c0a1">' . substr(PROJECT_NAME, 2)  . ' project template.</span></h2>';
;?>

<p>You can read more about <strong>how the project works</strong> by selecting <span class="highlight"><b>About Project</b></span> from the Menu.</p>
<p>You can also check <strong>how the application reads data from TXT file and Database</strong> by selecting <span class="highlight"><b>Car List</b></span> from Menu.</p>

<?php include VIEW . 'footer.phtml';?>