<?php include VIEW . 'header.phtml';?>

<?php include VIEW . '/car/subheader.phtml';?>

<h2> Executed <span class="highlight">GetVehicles()</span> stored procedure </h2>


<?php
    if(array_key_exists('cars', $this->view_data)){
        $table = '<table border=1><tr><th>id</th><th>Brand</th><th>Model</th><th>Year</th></tr>';

        foreach($this->view_data['cars'] as  $car){
                
                $table.= '<tr>';
                
                    $table.= '<td>' . $car['id'] . '</td>';
                    $table.= '<td>' . $car['brand'] . '</td>';
                    $table.= '<td>' . $car['model'] . '</td>';
                    $table.= '<td>' . $car['year'] . '</td>';

                $table.= '</tr>';
        }

        $table.= '</table>';

        echo $table;

        $this->view_data['cars']->close();
    }
?>

<?php include VIEW . 'footer.phtml';?>